### ISSUE TITLE
Repository link on crates.io/lib.rs points to ndshape repo.

### ISSUE THREAD

**Issue by BGR360** [bonsairobo/ilattice-rs#2]
<img width="292" alt="image" src="https://user-images.githubusercontent.com/13339928/150663768-9f07a0ef-3bb7-4cfd-b968-26e4afd69cfb.png">

**Comment by bonsairobo** [comment]
Right I believe this is taken care of on main. I will need to release a new version.

**Comment by naomijub** [comment]
Should be fixed on version 0.3 https://crates.io/crates/ilattice
